name: 'Performance comparison'
 
on:
  pull_request:
 
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # needed to post PR comments
 
    steps:
      - uses: julia-actions/setup-julia@latest
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          path: branch
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          path: main
      - name: Run Performance Test Main
        run: |
          julia --project=main/test -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(), "main"))); Pkg.instantiate()'
          julia -t 4 --project=main/test main/test/performance/bilinear_delta_benchmark.jl | tee main_output.txt
      - name: Run performance Test Branch
        run: |
          julia --project=branch/test -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(), "branch"))); Pkg.instantiate()'
          julia -t 4 --project=branch/test branch/test/performance/bilinear_delta_benchmark.jl | tee branch_output.txt
      - name: Read main results
        id: main_results
        run: |
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          cat main_output.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Read branch results
        id: branch_results
        run: |
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          cat branch_output.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Find comment
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Performance Results
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Performance Results
            Main
            ```
            ${{ steps.main_results.outputs.body }}
            ```
            This branch
            ```
            ${{ steps.branch_results.outputs.body }}
            ```
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Performance Results
            Main
            ```
            ${{ steps.main_results.outputs.body }}
            ```
            This branch
            ```
            ${{ steps.branch_results.outputs.body }}
            ```
          edit-mode: replace